# name: Publish to GH Pages
# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v3
#         with:
#           submodules: true

#       - name: Checkout destination
#         uses: actions/checkout@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           ref: gh-pages
#           path: built-site

#       - name: Setup Hugo
#         run: |
#           curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.118.2/hugo_extended_0.118.2_linux-amd64.tar.gz'
#           tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          
#       - name: Build
#         run: ${RUNNER_TEMP}/hugo

#       - name: Deploy
#         if: github.ref == 'refs/heads/main'
#         run: |
#           cp -R public/* ${GITHUB_WORKSPACE}/built-site/
#           cd ${GITHUB_WORKSPACE}/built-site
#           git add .
#           git config user.name 'dhij'
#           git config user.email 'davidhwang.ij@gmail.com'
#           git commit -m 'Updated site'
#           git push      


name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public